--liquibase formatted sql

--changeset ilya:1
create table coffee_machines (
    id int generated by default as identity primary key,
    has_water boolean not null,
    has_ground_coffee boolean not null,
    has_coffee boolean not null,
    enabled boolean not null
);
--rollback drop table coffee_machines